#!/bin/sh

wget --version >/dev/null 2>/dev/null || { echo "wget program required"; exit; }
basename --version >/dev/null 2>/dev/null || { echo "basename program required"; exit; }
dirname --version >/dev/null 2>/dev/null || { echo "dirname program required"; exit; }

if [ "x$1" = "x" ]; then
    echo "please use path to your toolchain, with toolchain prefix, e.g /usr/bin/armv7a-hardfloat-linux-gnueabi-"
    exit
fi

DIR=`dirname $1`
if [ $DIR != "." ]; then
	echo -e "path:\t$DIR"
	PATH=`dirname $1`:$PATH
fi

CROSS_COMPILE=$(basename $1)
HOST=${CROSS_COMPILE:0:-1}
echo -e "cc:\t$CROSS_COMPILE"
echo -e "host:\t$HOST"
ARCH=$(
	IFS=-
	set -- $HOST
	echo $1
)
echo -e "arch:\t$ARCH"

${CROSS_COMPILE}gcc --version >/dev/null || { echo "${CROSS_COMPILE}gcc was not found"; exit; }

export PATH
export HOST
export CROSS_COMPILE
export ARCH

function download {
    mkdir .sources 2> /dev/null
    URL=$1
    FILE=`basename $URL`
    DST=.sources/$FILE
    if [ ! -e $DST ]; then
        wget -o .sources/wget.log -c $URL -O $DST.partial || { echo "failed downloading $URL"; exit; }
        mv $DST.partial $DST
    fi
    echo $DST
}

function try {
    $*
    R=$?
    if [ $R -ne 0 ]; then
        echo "command $* failed"
        exit 1
    fi
}

function unpack {
    SRC=$1
    DST=$2
    mkdir -p .build 2>/dev/null
    if [ ! -e .build/$DST ]; then
        tar xf $SRC -C .build
    fi
}

function log {
    echo "${PACKAGE}: $*"
}

function append {
    SRC=$1
    tar --append --file=$ROOTFS --owner=0 --group=0 .
}

JOBS=8
ROOTFS=`pwd`/root.tar

rm -rf .install
mkdir .install

export INSTALL_DIR=`pwd`/.install
export BUILD_DIR=`pwd`/.build

export CC=${CROSS_COMPILE}gcc
export CXX=${CROSS_COMPILE}g++

rm -f $ROOTFS

. packages/layout

. packages/busybox

. packages/bzip2
. packages/lzo
. packages/zlib

. packages/e2fsprogs
. packages/mtd-utils

. packages/libpng
. packages/libjpeg-turbo
. packages/freetype

. packages/openssl
. packages/libnl
#. packages/wpa-supplicant #need kernel headers

pushd .build/layout
append
popd

pushd .install
append
popd

rm -rf .rootfs
mkdir .rootfs

tar xf root.tar -C .rootfs \
./bin ./data ./dev ./etc ./lib ./linuxrc ./media ./proc ./sbin ./sys \
./tmp ./usr/bin ./usr/lib ./var

echo OK
